--INSERTS ZONAS--
INSERT INTO TONT_ZONAS VALUES ('AF', 'Africa');
INSERT INTO TONT_ZONAS VALUES ('AN', 'Antarctica');
INSERT INTO TONT_ZONAS VALUES ('AS', 'Asia');
INSERT INTO TONT_ZONAS VALUES ('EU', 'Europe');
INSERT INTO TONT_ZONAS VALUES ('NA', 'North America');
INSERT INTO TONT_ZONAS VALUES ('OC', 'Oceania');
INSERT INTO TONT_ZONAS VALUES ('SA', 'South America');

--INSERTS PAISES--
INSERT INTO TONT_PAISES VALUES ('AD', 'Andorra', 'EU');
INSERT INTO TONT_PAISES VALUES ('AE', 'United Arab Emirates', 'AS');
INSERT INTO TONT_PAISES VALUES ('AF', 'Afghanistan', 'AS');
INSERT INTO TONT_PAISES VALUES ('AL', 'Albania', 'EU');
INSERT INTO TONT_PAISES VALUES ('AM', 'Armenia', 'EU');
INSERT INTO TONT_PAISES VALUES ('AO', 'Angola', 'AF');
INSERT INTO TONT_PAISES VALUES ('AQ', 'Antarctica', 'AN');
INSERT INTO TONT_PAISES VALUES ('AR', 'Argentina', 'SA');
INSERT INTO TONT_PAISES VALUES ('AT', 'Austria', 'EU');
INSERT INTO TONT_PAISES VALUES ('AU', 'Australia', 'OC');
INSERT INTO TONT_PAISES VALUES ('BO', 'Bolivia', 'SA');
INSERT INTO TONT_PAISES VALUES ('BR', 'Brazil', 'SA');
INSERT INTO TONT_PAISES VALUES ('CO', 'Colombia', 'SA');
INSERT INTO TONT_PAISES VALUES ('CR', 'Costa Rica', 'NA');
INSERT INTO TONT_PAISES VALUES ('CU', 'Cuba', 'NA');
INSERT INTO TONT_PAISES VALUES ('CV', 'Cape Verde', 'AF');
INSERT INTO TONT_PAISES VALUES ('MX', 'Mexico', 'NA');
INSERT INTO TONT_PAISES VALUES ('US', 'United States of America', 'NA');
INSERT INTO TONT_PAISES VALUES ('UY', 'Uruguay', 'SA');
INSERT INTO TONT_PAISES VALUES ('VE', 'Venezuela', 'SA');

--INSER AVES--
INSERT INTO TONT_AVES VALUES ('AV001', false, 'Anhima cornuta', 'Aruco');

INSERT INTO TONT_AVES_PAIS VALUES ('AV001','CO');
INSERT INTO TONT_AVES_PAIS VALUES ('AV001','VE');